import { SideBar } from "sidebar.slint";
import { MainBox } from "main.slint";
export component Container  inherits Rectangle {
    border-top-left-radius: 10px;   // 设置矩形左上角的圆角半径为 10 像素
    border-top-right-radius: 10px;  // 设置矩形右上角的圆角半径为 10 像素

    // 创建一个水平布局容器，用于横向排列子组件
    HorizontalLayout {
        
        // 定义侧边栏组件实例并命名为 siderbar
        siderbar := SideBar {
            width: 210px;
        }

        // 定义主内容区域组件实例并命名为 mainbox
        mainbox := MainBox {
            horizontal-stretch: 1;
        }
    }
}