import { Singer } from "../pages/singer/singer.slint";
import { Download } from "../pages/download/download.slint";
import { Recently } from "../pages/recently/recently.slint";
import { Like } from "../pages/like/like.slint";
import { Picked } from "../pages/picked/picked.slint";
import { State } from "../pages/states/state.slint";
import { MusicHouse } from "../pages/music-house/music-house.slint";
import { Home } from "../pages/home/home.slint";
import { PageType, HistoryStore, PageBoxStore } from "global.slint";
import { Theme } from "../pages/theme/theme.slint";
export component PageBox inherits Rectangle {

    // 创建一个垂直布局容器，用于组织子组件
    VerticalLayout {
        padding: 30px;

        // Singer {}


        box := Rectangle {
            clip: true; // 启用裁剪，超出容器范围的内容将被隐藏

            // 创建一个水平布局，用于横向排列不同的页面
            HorizontalLayout {
                
                // 设置 X 轴位置，根据 PageBoxStore 的 position-offset 动态偏移
                // 偏移量为 -position-offset 乘以 box 的宽度，实现页面切换效果
                x: -PageBoxStore.position-offset * box.width;

                alignment: start;   // 设置对齐方式为起始位置（左侧对齐）

                Home {
                    width: 100%;
                }

                Picked {
                    width: 100%;
                }

                State {
                    width: 100%;
                }

                MusicHouse {
                    width: 100%;
                }

                Like {
                    width: 100%;
                }

                Recently {
                    width: 100%;
                }

                Download {
                    width: 100%;
                }

                Singer {
                    width: 100%;
                }

                Theme {
                    width: 100%;
                }
            }
        }

    }
}