import { QImage } from "../components/qimage.slint";
import { ScrollView } from "std-widgets.slint";
import { VinylStore } from "global.slint";

export component Vinyl inherits Rectangle {
    
    y: VinylStore.position-y;   // 设置 y 坐标，根据 VinylStore 的 position 属性动态计算
    background: #535252;      // 设置背景颜色为深灰色
    
    border-top-left-radius: 10px;   // 设置顶部左右圆角为 10px，创建圆角效果
    border-top-right-radius: 10px;

    // 为 y 属性添加动画效果
    animate y {
        duration: 500ms;    // 动画持续时间为 500 毫秒
    }

    // 子矩形，作为主要内容容器
    Rectangle {
        width: 600px;
        height: 400px;

        // 使用水平布局管理子元素
        HorizontalLayout {
            alignment: stretch; // 设置布局对齐方式为拉伸填充

            // 左侧矩形容器
            Rectangle {
                // 设置水平拉伸系数为 1，与右侧矩形均分空间
                horizontal-stretch: 1;

                // 唱片样式的圆形容器
                Rectangle {
                    width: 200px;
                    height: 200px;
                    
                    background: #000;   // 设置黑色背景
                    border-radius: self.width / 2;  // 设置圆角半径为宽度的一半，形成圆形

                    // 内层圆形容器
                    Rectangle {
                        width: 160px;
                        height: 160px;
                        
                        border-radius: self.width / 2;  // 同上，形成圆形
                        
                        clip: true;     // 启用剪切，超出部分将被裁剪


                        // 显示图片的组件
                        QImage {
                            
                            width: parent.width;    // 宽度与父容器一致
                            height: self.width;     // 高度与宽度保持一致，形成正方形
                            source: @image-url("../../assets/katong8.png");
                            
                            rotation: 90deg * animation-tick() / 3s;    // 设置旋转动画，每3秒旋转90度
                        }
                    }
                }
            }

            // 右侧矩形容器
            Rectangle {
                
                horizontal-stretch: 1;  // 设置水平拉伸系数为 1，与左侧矩形均分空间

                // 内容显示区域
                Rectangle {
                    width: 200px;

                    // 使用垂直布局管理子元素
                    VerticalLayout {
                        
                        alignment: stretch; // 设置布局对齐方式为拉伸填充
                        spacing: 20px;      // 子元素间距为 20px

                        Text {
                            text: "晴天";           
                            font-size: 20px;        
                            color: #fff;           
                        }

                        // 包含滚动视图的矩形容器
                        Rectangle {
                            // 滚动视图组件
                            ScrollView {
                                // 始终隐藏垂直滚动条
                                vertical-scrollbar-policy: always-off;

                                // 滚动内容区域的垂直布局
                                VerticalLayout {
                                    // 子元素间距为 5px
                                    spacing: 5px;

                                    for item in [
                                        "故事的小黄花",
                                        "从出生那年就飘着",
                                        "童年的荡秋千",
                                        "随记忆一直晃到现在",
                                        "Re So So Si Do Si La",
                                        "So La Si Si Si Si La Si La So",
                                        "吹着前奏 望着天空",
                                        "我想起花瓣试着掉落",
                                        "为你翘课的那一天",
                                        "花落的那一天",
                                        "教室的那一间",
                                        "我怎么看不见",
                                        "消失的下雨天",
                                        "我好想再淋一遍",
                                        "没想到 失去的勇气我还留着",
                                        "好想再问一遍",
                                        "你会等待还是离开",
                                        "刮风这天 我试过握着你手",
                                        "但偏偏 雨渐渐",
                                        "大到我看你不见",
                                        "还要多久 我才能在你身边",
                                        "等到放晴的那天",
                                        "也许我会比较好一点",
                                        "从前从前 有个人爱你很久",
                                        "但偏偏 风渐渐",
                                        "把距离吹得好远",
                                        "好不容易 又能再多爱一天",
                                        "但故事的最后",
                                        "你好像还是说了 拜拜",
                                        "为你翘课的那一天",
                                        "花落的那一天",
                                        "教室的那一间",
                                        "我怎么看不见",
                                        "消失的下雨天",
                                        "我好想再淋一遍",
                                        "没想到 失去的勇气我还留着",
                                        "好想再问一遍",
                                        "你会等待还是离开",
                                        "刮风这天 我试过握着你手",
                                        "但偏偏 雨渐渐",
                                        "大到我看你不见",
                                        "还要多久 我才能在你身边",
                                        "等到放晴的那天",
                                        "也许我会比较好一点",
                                        "从前从前 有个人爱你很久",
                                        "偏偏 风渐渐",
                                        "把距离吹得好远",
                                        "好不容易 又能再多爱一天",
                                        "但故事的最后",
                                        "你好像还是说了 拜拜",
                                        "刮风这天 我试过握着你手",
                                        "但偏偏 雨渐渐",
                                        "大到我看你不见",
                                        "还要多久 我才能够在你身边",
                                        "等到放晴那天",
                                        "也许我会比较好一点",
                                        "从前从前 有个人爱你很久",
                                        "但偏偏 雨渐渐",
                                        "把距离吹得好远",
                                        "好不容易 又能再多爱一天",
                                        "但故事的最后",
                                        "你好像还是说了拜"
                                    ]: Text {
                                        color: #fff;
                                        text: item;
                                        font-size: 14px;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

}