import { QImage } from "../components/qimage.slint";
import { ScrollView } from "std-widgets.slint";
import { VinylStore } from "global.slint";
export component Vinyl inherits Rectangle {
    y: VinylStore.position-y;
    background: #535252;
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;

    animate y {
         duration: 500ms;
    }

    Rectangle {
        width: 600px;
        height: 400px;

        // background: #fff;

        HorizontalLayout {
            alignment: stretch;

            Rectangle {
                horizontal-stretch: 1;

                Rectangle {
                    width: 200px;
                    height: 200px;
                    background: #000;
                    border-radius: self.width / 2;

                    Rectangle {
                        width: 160px;
                        height: 160px;
                        border-radius: self.width / 2;
                        clip: true;

                        // background: #fff;

                        QImage {
                            width: parent.width;
                            height: self.width;
                            source: @image-url("../../assets/katong8.png");
                            rotation: 90deg * animation-tick() / 3s;
                        }
                    }
                }
            }

            Rectangle {
                horizontal-stretch: 1;

                Rectangle {
                    width: 200px;

                    VerticalLayout {
                        alignment: stretch;
                        spacing: 20px;

                        Text {
                            text: "晴天";
                            font-size: 20px;
                            color: #fff;
                        }

                        Rectangle {

                            ScrollView {
                                vertical-scrollbar-policy: always-off;

                                VerticalLayout {
                                    spacing: 5px;

                                    for item in [
                                        "故事的小黄花",
                                        "从出生那年就飘着",
                                        "童年的荡秋千",
                                        "随记忆一直晃到现在",
                                        "Re So So Si Do Si La",
                                        "So La Si Si Si Si La Si La So",
                                        "吹着前奏 望着天空",
                                        "我想起花瓣试着掉落",
                                        "为你翘课的那一天",
                                        "花落的那一天",
                                        "教室的那一间",
                                        "我怎么看不见",
                                        "消失的下雨天",
                                        "我好想再淋一遍",
                                        "没想到 失去的勇气我还留着",
                                        "好想再问一遍",
                                        "你会等待还是离开",
                                        "刮风这天 我试过握着你手",
                                        "但偏偏 雨渐渐",
                                        "大到我看你不见",
                                        "还要多久 我才能在你身边",
                                        "等到放晴的那天",
                                        "也许我会比较好一点",
                                        "从前从前 有个人爱你很久",
                                        "但偏偏 风渐渐",
                                        "把距离吹得好远",
                                        "好不容易 又能再多爱一天",
                                        "但故事的最后",
                                        "你好像还是说了 拜拜",
                                        "为你翘课的那一天",
                                        "花落的那一天",
                                        "教室的那一间",
                                        "我怎么看不见",
                                        "消失的下雨天",
                                        "我好想再淋一遍",
                                        "没想到 失去的勇气我还留着",
                                        "好想再问一遍",
                                        "你会等待还是离开",
                                        "刮风这天 我试过握着你手",
                                        "但偏偏 雨渐渐",
                                        "大到我看你不见",
                                        "还要多久 我才能在你身边",
                                        "等到放晴的那天",
                                        "也许我会比较好一点",
                                        "从前从前 有个人爱你很久",
                                        "偏偏 风渐渐",
                                        "把距离吹得好远",
                                        "好不容易 又能再多爱一天",
                                        "但故事的最后",
                                        "你好像还是说了 拜拜",
                                        "刮风这天 我试过握着你手",
                                        "但偏偏 雨渐渐",
                                        "大到我看你不见",
                                        "还要多久 我才能够在你身边",
                                        "等到放晴那天",
                                        "也许我会比较好一点",
                                        "从前从前 有个人爱你很久",
                                        "但偏偏 雨渐渐",
                                        "把距离吹得好远",
                                        "好不容易 又能再多爱一天",
                                        "但故事的最后",
                                        "你好像还是说了拜"
                                    ]: Text {
                                        color: #fff;
                                        text: item;
                                        font-size: 14px;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

}